version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/Docker/builder/rootfs/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
