name: "Cookiecutter in Github Actions"
description: "Generate from a cookiecutter template as part of your github workflow"
author: "Andrew Herrington"
inputs:
  cookiecutterValues:
    description: "Json blob to pass to the cookiecutter template. Any values not filled in will be set to template's default"
    required: false
    default: '{}'
  template:
    description: "A directory containing a project template directory (or zip file), or a URL to a git repository."
    required: true
  templateCheckout:
    description: "The branch, tag or commit ID to checkout after clone."
    required: false
  templateDirectory:
    description: "Relative path to a cookiecutter template in a repository."
    required: false
  outputDir:
    description: "Where to output the generated project dir into."
    default: "."
    required: false
  overwrite:
    description: "Overwrite files if they already exist in outputDir if true. Takes priority over 'skip'"
    required: false
    default: "false"
  skip:
    description: "Skip files if they already exist in outputDir if true. Ignored if 'overwrite' is true"
    required: false
    default: "false"
  zipPassword:
    description: "If your template zip is password protected, put your password here"
    required: false
  acceptHooks:
    description: "Accept pre and post hooks if set to true."
    required: false
    default: "true"
outputs:
  outputDir:
    description: "Directory the cookiecutter outputted to"
runs:
  using: "docker"
  image: "docker://ghcr.io/andrewthetechie/gha-cookiecutter:v1.3.2" # x-release-please-version
branding:
  icon: 'layers'
  color: 'blue'
