# Tests athe github action on each push
name: Action Integration Test
on:
  push:
  pull_request:
jobs:
  action-integration-testing:
    name: Action Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Update action.yml to use dockerfile
        uses: rmeneely/update-yaml@v1
        with:
          infile: action.yml
          varlist: "runs.image=Dockerfile"
      - name: Test action
        id: test-action
        # test with the local checkout of the action
        uses: ./
        with:
          template: https://github.com/cjolowicz/cookiecutter-hypermodern-python.git
          cookiecutterValues: '{
            "project_name": "integration-test"
          }'
      - name: Check that our created template exists
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "integration-test"
      - name: Check ls
        run: |
          ls
      - name: Check check_files
        run: |
          test "${{ steps.check_files.outputs.files_exists }}" == "true"
      - name: Check outputs
        run: |
          test "${{ steps.test-action.outputs.outputDir }}" == "/github/workspace/integration-test"
