name: Lint
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.11"
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - run: go install github.com/rhysd/actionlint/cmd/actionlint@latest
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: make install-requirements
      - name: Run Pre-commit
        uses: pre-commit/action@v3.0.0
